services:
  app:
    build:
      context: .
      dockerfile: editor.dockerfile
    container_name: quassar
    ports:
      - "${QUASSAR_PORT}:8080"
    environment:
      - HOME_DIR=/root/data
      - PORT=8080
      - TITLE=Quassar
      - FEDERATION_URL=
      - LANGUAGE_ARTIFACTORY=https://artifactory.intino.io/artifactory/releases
    volumes:
      - shared_volume:/root/data

volumes:
  shared_volume:
    driver: local
    driver_opts:
      type: none
      device: ${QUASSAR_HOME}
      o: bind