services:
  app:
    build:
      context: .
      dockerfile: editor.dockerfile
    container_name: quassar
    ports:
      - "${QUASSAR_PORT}:8080"
    environment:
      - HOME_DIR=/root/data
      - PORT=8080
      - TITLE=Quassar
      - FEDERATION_URL=
      - LANGUAGE_ARTIFACTORY=https://artifactory.intino.io/artifactory/releases
    volumes:
      - ${QUASSAR_HOME}:/root/data
